[package]
name = "meld"
version = "0.1.0"
authors = ["Alan Darmasaputra <alan@accelbyte.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
