on:
  push:
    branches: [master]
  pull_request:

name: Build, Test

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all --all-targets --all-features -- -D warnings
      - run: cargo test --all --verbose
