on:
  push:
    branches:
      - master

name: Build, Test, Publish

jobs:
  build-test-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all --all-targets --all-features -- -D warnings
      - run: cargo test --all --verbose
      - run: cargo login ${CRATES_IO_TOKEN}
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
      - run: cargo publish
